#include "activity.h"
#include <types.h>
#include "deployment.h"
#include <core/thread.h>
#include <assert.h>
#include <core/time.h>
#include <core/partition.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
uint32_t pok_threads[POK_CONFIG_NB_THREADS];
int main (void)
{

  pok_thread_attr_t tattr;
  pok_ret_t ret;
  ret = pok_thread_attr_init (&(tattr));
  ASSERT_RET(ret);
  tattr.entry = thr2_job;
  tattr.deadline = pok_time_milliseconds (5000);
  tattr.period = pok_time_milliseconds (5000);
  tattr.stack_size = 30000;
  tattr.time_capacity = pok_time_milliseconds (10);
  ret = pok_thread_create (&(pok_threads[1]), &(tattr));
  ASSERT_RET(ret);
  /*  This thread was mapped from a thread component containedin this */
  /*  process. The function it executes is also generatedin the file */
  /*  activity.c.*/
  pok_partition_set_mode (POK_PARTITION_MODE_NORMAL);
  /*  Now, we created all resources of the process. Consequently,this thread */
  /*  will not be used any more and it will be keptin a dormant state. By */
  /*  doing that, we also allow one morethread in this partition*/
  return (0);
}


