BUILD = --models=layers.aadl,main.aadl,memories.aadl,partitions.aadl,runtime.aadl,subprograms.aadl,threads.aadl,types.aadl,rtl8029.aadl --no-run --root=main.i
TESTS = compile-x86

include $(POK_PATH)/misc/mk/examples.mk
