#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2025 POK team

platform: !mux
    x86_gcc:
        qemu: qemu-system-i386
        proc: 1
        compiler: gcc -m32 -Wall -Wextra -Werror -O3
tests: !mux
    hello_world:
        dir: hello_world_shutdown_qemu
    test_modulo_div_64:
        dir: test_modulo_div_64
    test_assert:
        dir: assert
    limit_threads:
        dir: limit_threads
    semaphore_sched:
        dir: semaphore_sched
    test_printf:
        dir: test_printf
    test_events:
        dir: events
    test_mutexes:
        dir: mutexes


