.SILENT:

AR_ppc=/usr/local/bin/powerpc-elf-ar rcs
AR_sparc=/usr/local/bin/sparc-elf-ar rcs
AR_x86=/bin/ar rcs
AWK=/bin/gawk
CAT=/bin/cat
CC_ppc=/usr/local/bin/powerpc-elf-gcc
CC_sparc=/usr/local/bin/sparc-elf-gcc
CC_x86=/bin/gcc
CD=cd
CONFIG_CFLAGS=-W -Wall -g -m32
CONFIG_LDFLAGS=--warn-common
CONFIG_QEMU_x86= -fda $(POK_PATH)/misc/grub-boot-only.img 
COPY=/bin/cp
CP=/bin/cp
CXX_x86=/bin/g++
ECHO=/bin/echo
ELF_MODE=elf_i386
GREP=/bin/grep
GZIP=/bin/gzip
INSTRUMENTATION=0
KILL=/bin/kill
LD_ppc=/usr/local/bin/powerpc-elf-ld
LD_sparc=/usr/local/bin/sparc-elf-ld
LD_x86=/bin/ld
MKDIR=/bin/mkdir
MV=/bin/mv
OBJCOPY_ppc=/usr/local/bin/powerpc-elf-objcopy
OBJCOPY_sparc=/usr/local/bin/sparc-elf-objcopy
OBJCOPY_x86=/bin/objcopy
OBJDUMP_ppc=/usr/local/bin/powerpc-elf-objdump
OBJDUMP_sparc=/usr/local/bin/sparc-elf-objdump
OBJDUMP_x86=/bin/objdump
PERL=/bin/perl
QEMU_ppc=/bin/qemu-system-ppc
QEMU_sparc=/bin/qemu-system-sparc
QEMU_x86=/bin/qemu-system-i386
RANLIB_ppc=/usr/local/bin/powerpc-elf-ranlib
RANLIB_sparc=/usr/local/bin/sparc-elf-ranlib
RANLIB_x86=/bin/ranlib
RM=/bin/rm -r -f
SED=/bin/sed
SLEEP=/bin/sleep
TOUCH=/bin/touch
TSIM_sparc=/usr/local/bin/tsim-leon3
