#include "gtypes.h"
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_receive(pingpong__integer input);

/****************************/
/* pingpong__hello_part2   */
/***************************/

void pingpong__hello_part2(pingpong__integer input) { user_receive(input); }
