#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define POK_GENERATED_CODE 1

#define POK_NEEDS_STDIO 1

#define POK_CONFIG_NB_THREADS 3

#define POK_CONFIG_STACKS_SIZE 8192

#define POK_NEEDS_ARINC653_TIME 1

#define POK_NEEDS_ARINC653_SAMPLING 1

#define POK_NEEDS_ARINC653_PROCESS 1

#define POK_NEEDS_ARINC653_ERROR 1

#define POK_NEEDS_ARINC653_PARTITION 1

#define POK_USE_GENERATED_ERROR_HANDLER 1

#endif
