/*
 *                               POK header
 * 
 * The following file is a part of the POK project. Any modification should
 * made according to the POK licence. You CANNOT use this file or a part of
 * this file is this part of a file for your own project
 *
 * For more information on the POK licence, please see our LICENCE FILE
 *
 * Please follow the coding guidelines described in doc/CODING_GUIDELINES
 *
 *                                      Copyright (c) 2007-2009 POK team 
 *
 * Created by laurent on Tue Dec 22 14:57:52 2009 
 */

#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define POK_GENERATED_CODE 1

#define POK_NEEDS_STDIO 1

#define POK_CONFIG_NB_THREADS 3

#define POK_CONFIG_STACKS_SIZE 8192

#define POK_NEEDS_ARINC653_TIME 1

#define POK_NEEDS_ARINC653_SAMPLING 1

#define POK_NEEDS_ARINC653_PROCESS 1

#define POK_NEEDS_ARINC653_ERROR 1

#define POK_NEEDS_ARINC653_PARTITION 1

#define POK_USE_GENERATED_ERROR_HANDLER 1

#endif
