#ifndef __OCARINA_GENERATED_GTYPES_H_
#define __OCARINA_GENERATED_GTYPES_H_
#include <arinc653/types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

typedef int pingpong__integer;

#endif
