#include "deployment.h"
#include "subprograms.h"
#include <arinc653/time.h>
#include <arinc653/types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
/*  Periodic task : thr2*/

/***************/
/* thr2_job   */
/**************/

void *thr2_job() {

  RETURN_CODE_TYPE ret;
  while (1) {
    /*  Call implementation*/
    test__hello_part2();
    PERIODIC_WAIT(&(ret));
  }
}
