/*
 *                               POK header
 *
 * The following file is a part of the POK project. Any modification should
 * be made according to the POK licence. You CANNOT use this file or a part
 * of a file for your own project.
 *
 * For more information on the POK licence, please see our LICENCE FILE
 *
 * Please follow the coding guidelines described in doc/CODING_GUIDELINES
 *
 *                                      Copyright (c) 2007-2020 POK team
 */

#include "deployment.h"
#include "subprograms.h"
#include <arinc653/time.h>
#include <arinc653/types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
/*  Periodic task : thr2*/

/***************/
/* thr2_job   */
/**************/

void *thr2_job() {

  RETURN_CODE_TYPE ret;
  while (1) {
    /*  Call implementation*/
    test__hello_part2();
    PERIODIC_WAIT(&(ret));
  }
}
