portqueueingreceive.o: portqueueingreceive.c
portcreate.o: portcreate.c
portflushall.o: portflushall.c
portvirtualid.o: portvirtualid.c
portvirtualnbdestinations.o: portvirtualnbdestinations.c
queueinit.o: queueinit.c
portvirtualdestination.o: portvirtualdestination.c
portutils.o: portutils.c
portsamplingread.o: portsamplingread.c
portinit.o: portinit.c
portqueueingcreate.o: portqueueingcreate.c
portsamplingid.o: portsamplingid.c
portsamplingstatus.o: portsamplingstatus.c
portqueueingid.o: portqueueingid.c
ressources.o: ressources.c
portqueueingsend.o: portqueueingsend.c
portsamplingwrite.o: portsamplingwrite.c
portvirtualgetglobal.o: portvirtualgetglobal.c
portqueueingstatus.o: portqueueingstatus.c
portsamplingcreate.o: portsamplingcreate.c
