#include <gtypes.h>
#include <libc/stdio.h>

/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/***************************/
/* user_display_manager   */
/**************************/

void user_display_manager(types__pagerequestcmd dm_to_display_request,
                          types__pagecontent *dm_to_display_page,
                          types__pagecontent dm_to_pcm_page,
                          types__pagerequestcmd *dm_to_pcm_request) {
  printf("[DM] USER DISPLAY MANAGER\n");
}
