/*
 *                               POK header
 * 
 * The following file is a part of the POK project. Any modification should
 * made according to the POK licence. You CANNOT use this file or a part of
 * this file is this part of a file for your own project
 *
 * For more information on the POK licence, please see our LICENCE FILE
 *
 * Please follow the coding guidelines described in doc/CODING_GUIDELINES
 *
 *                                      Copyright (c) 2007-2009 POK team 
 *
 * Created by julien on Thu Dec  3 10:21:25 2009 
 */

#include <gtypes.h>
#include <libc/stdio.h>

/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/


/***************************/
/* user_display_manager   */ 
/**************************/

void user_display_manager 
    (types__pagerequestcmd dm_to_display_request,
    types__pagecontent* dm_to_display_page,
    types__pagecontent dm_to_pcm_page,
    types__pagerequestcmd* dm_to_pcm_request)
{
   printf ("[DM] USER DISPLAY MANAGER\n");
}



