BUILD = --models=model.aadl,partitions.aadl,runtime.aadl,subprograms.aadl,threads.aadl,types.aadl,memories.aadl --no-run --arinc653

TESTS = compile-x86 compile-ppc
include $(POK_PATH)/misc/mk/examples.mk
