/*
 *                               POK header
 * 
 * The following file is a part of the POK project. Any modification should
 * made according to the POK licence. You CANNOT use this file or a part of
 * this file is this part of a file for your own project
 *
 * For more information on the POK licence, please see our LICENCE FILE
 *
 * Please follow the coding guidelines described in doc/CODING_GUIDELINES
 *
 *                                      Copyright (c) 2007-2013 POK team 
 *
 * Created by phipse on Wed May 15 13:12:32 2013 
 */

#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define POK_GENERATED_CODE 1

#define POK_NEEDS_LIBC_STDIO 1

#define POK_NEEDS_CONSOLE 1

#define POK_CONFIG_NB_THREADS 2

#define POK_CONFIG_STACKS_SIZE 30000

#define POK_NEEDS_THREADS 1

#define POK_NEEDS_TIME 1

#define POK_NEEDS_PARTITIONS 1

#endif
