#include "subprograms.h"
#include <assert.h>
#include <core/event.h>
#include <core/lockobj.h>
#include <core/thread.h>
#include <errno.h>
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
/*  Periodic task : thr1*/
extern pok_event_id_t input_id;
void *thr1_job(void) {

  while (1) {
    /*  Send the OUT ports*/
    pok_event_signal(input_id);
    pok_thread_period();
  }
}

/*  Periodic task : thr2*/
extern pok_event_id_t input_id;
void *thr2_job(void) {

  pok_ret_t ret;
  while (1) {
    /*  Get the IN ports values*/
    ret = pok_event_wait(input_id, 0);
    assert(!ret);
    /* :: Yes if commentary :: */ if (ret == POK_ERRNO_OK) {
      pok_testevents__spg_receive_event();
    }
    pok_thread_period();
  }
}
