#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2025 POK team

target:
    arch: arm
    bsp: stm32f4

partitions:
    - name: part1
      features: [assert, console, libc]
      scheduler: RR
      threads:
          count: 2
          features: [sleep]
      size: 32kB
      objects: ["main.o"]

kernel:
    features: [debug]
    scheduler:
        major_frame: 1s
        slots:
            - partition: part1
              duration: 1s
