// This file has been automatically generated by gen_dependencies
// from the file dependencies.yaml. Do not make manual modifications there or
// they will be lost.

#ifndef __KERNEL_DEPENDENCIES_H__
#define __KERNEL_DEPENDENCIES_H__

#ifdef POK_NEEDS_ASSERT

#ifndef POK_NEEDS_DEBUG
#define POK_NEEDS_DEBUG 1
#endif // !POK_NEEDS_DEBUG

#ifndef POK_NEEDS_SHUTDOWN
#define POK_NEEDS_SHUTDOWN 1
#endif // !POK_NEEDS_SHUTDOWN

#endif // POK_NEEDS_ASSERT

#ifdef POK_NEEDS_ERROR_HANDLING

#ifndef POK_NEEDS_SCHED_STOP_SELF
#define POK_NEEDS_SCHED_STOP_SELF 1
#endif // !POK_NEEDS_SCHED_STOP_SELF

#endif // POK_NEEDS_ERROR_HANDLING

#ifdef POK_NEEDS_THREAD_SUSPEND

#ifndef POK_NEEDS_SCHED_STOP_SELF
#define POK_NEEDS_SCHED_STOP_SELF 1
#endif // !POK_NEEDS_SCHED_STOP_SELF

#endif // POK_NEEDS_THREAD_SUSPEND

#endif // __KERNEL_DEPENDENCIES_H__
