#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2025 POK team

platform: !mux
    x86_gcc:
        qemu: qemu-system-i386
        proc: 4
        compiler: gcc -m32 -Wall -Wextra -Werror -O3
        timeout: 1800 # 30 minutes per test
tests: !mux
    events:
      dir: events
      affinity_max: 2
      partitions: 3
    mutexes:
      dir: mutexes
      affinity_max: 2
      partitions: 3
    semaphores:
      dir: semaphore_sched
      affinity_max: 2
      partitions: 4
